Build wrapper with BinaryBuilder
gridap/MiniQhull.jl pull request #25
Opened 2022-09-28 10:04 UTC by SimonDanisch

Needs https://github.com/JuliaPackaging/Yggdrasil/pull/5588 to be merged before we can merge.

2022-09-28 11:34 UTC, SimonDanisch commented
Alright, this might just work :) QhullMiniWrapper_jll got released and this passes tests locally!

2022-09-28 11:56 UTC, SimonDanisch commented
Hm so, ` outfile = fopen("/dev/null","w");` doesn't work on windows :( 
Can't we call `qh_new_qhull` and `qh_triangulate` directly in Julia from Qhull_jll? It does look that way on first sight..

I guess we also lost support for 1.3, which isn't so bad?

2022-09-28 12:09 UTC, SimonDanisch commented
As far as I can tell `"nul"` should be cross platform.
At least `ccall(:fopen, Ptr{Cvoid}, (Ptr{Cchar}, Ptr{Cchar}), "nul", "w")` works on both linux and windows for me...
But, now that I look at the qh_new_qhull docs, can't we just pass NULL to the error stream for the same effect?

2022-09-28 12:24 UTC, SimonDanisch commented
Will be fixed in https://github.com/JuliaRegistries/General/pull/69115#issuecomment-1260821446

2022-09-28 12:35 UTC, SimonDanisch commented
Alright, this passes tests now locally on windows as well...

2022-09-28 13:49 UTC, SimonDanisch commented
Yay :) I guess this needs to be released as a breaking version... 
I wouldn't want to put more time into trying to not break `MiniQhull.QHULL_WRAPPER_LOADED[]` or providing your own Qhull build...Hope that's acceptable!

2022-09-29 06:48 UTC, fverdugo requested changes
Hi @SimonDanisch,

thanks for doing this work! 

please find some minor comments.

2022-09-29 06:48 UTC, fverdugo commented on README.md
> +Custom installation of `Qhull` can be performed as described in the official [Qhull installation instructions](http://www.qhull.org/README.txt).
Is still possible to use a custom version of QHULL? It not, please remove this.

2022-09-29 06:48 UTC, fverdugo commented on README.md
Is this section still relevant?

2022-09-29 06:48 UTC, fverdugo commented on Project.toml
>  version = "0.3.1"
Please move it to the next breaking release, i.e., 0.4.0

2022-09-29 10:19 UTC, fverdugo approved these changes

2022-09-29 10:20 UTC, merged